config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
        sessions: 'users/sessions'
  }
  resources :posts do
    resources :comments
  end
  root to: "posts#index"
  get '/about' , to: 'pages#about'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :body, :presence => true, :length => { :minimum => 1 }
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :title, :presence => true, :length => { :minimum => 5 }
  validates :body, :presence => true, :length => { :minimum => 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery :except => [:destroy]
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
		@post = Post.find(params[:post_id])
    create_params = post_params
    create_params[:user_id] = @post.user_id
		@comment = @post.comments.create(create_params)

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end

  private
  def post_params
    params[:comment].permit(:body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end
end

app/controllers/posts/posts_controller.rb
class PostsController < ApplicationController

  def index

  end

  def show
  end

  def new
    @post = Post.new
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    # @posts = Post.all.order('created_at DESC')
    @posts = Post.page(params[:page]).per(3).order('created_at DESC')
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy!
      redirect_to root_path
    else
      render 'show'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def create
    create_params = post_params
    create_params[:user_id] = current_user.id
    @post = Post.new(create_params)

    if @post.save
			redirect_to root_url
		else
			render 'new'
		end
  end

  private

	def post_params
		params.require(:post).permit(:title, :body)
	end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<div class="">
  <p><%= comment.body %></p>
  <p>Created by:  <%= comment.user.email %></p>
  <p><%= time_ago_in_words(comment.created_at) %></p>
  <%= link_to 'Delete', [comment.post, comment], method: :delete,
    class: :button,
    data: { confirm: 'Are you sure?' }
  %>
</div>

app/views/comments/_form.html.erb
<%= simple_form_for ([@post, @post.comments.build]) do |f| %>
  <%= f.input :body %><br>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodeCourage</title>
  <meta name="keywords" content="HTML, Code, Rails, Ruby, Samarth, Asthana" />
  <meta name="description" content= "Personal blog of a Rails full stack developer sharing knowledge." />
  <meta name="author" content="Samarth Asthana" />
  <META name="ROBOTS" content="INDEX, FOLLOW">
  <meta http-equiv="content-type" content="text/html;charset=UTF-8">
  <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %> -->
  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Raleway:400,700' %>
  <%= javascript_include_tag "application" %>
  <!-- Bootstrap Core CSS -->
  <link href="css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom CSS -->
  <link href="stylesheets/simple-sidebar.css.scss" rel="stylesheet">
  <div class="alert-msg">
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </div>

<!-- <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js"></script> -->
<script src="http://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.2/modernizr.js"></script>
<script type="text/javascript">
//paste this code under head tag or in a seperate js file.
  // Wait for window load
  $( document).ready(function() {
    $(".se-pre-con").fadeOut("slow");;
  });
</script>
</head>
<body>
  <div class="se-pre-con"></div>
  <div id="wrapper">
    <!-- Sidebar -->
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
          <li class="sidebar-brand">
            <%= link_to 'Code Courage', root_path, :class => 'navbar-link' %>
          </li>
          <li>
            <%= link_to 'Blog', root_path, :class => 'navbar-link' %>
          </li>
          <li>
            <%= link_to 'About', about_path, :class => 'navbar-link' %>
          </li>
          <!-- <li>
            <%= link_to 'Contact', about_path, :class => 'navbar-link' %></a>
          </li> -->
        </ul>
    </div>
    <div class="col-lg-12 nopadding">
      <ul class="top-navbar">
        <li>
          <button type="button" id ="menu-toggle" class="btn btn-default" aria-label="Left Align">
            <span class="glyphicon glyphicon-align-left" aria-hidden="true"></span>
          </button>
          <%= link_to 'Home', root_path, :class => 'navbar-link' %>
          <% if user_signed_in? %>
            <% unless request.original_fullpath.to_s.include?('posts/new') %>
              | <%= link_to 'Add Post', new_post_path, :class => 'navbar-link' %>
            <% end %>
          <% end %>
        </li>
        <li class="nav-links">
          <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
        </li>
      </ul>
    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                </div>
                <%= yield %>
            </div>
        </div>
    </div>
    <!-- /#page-content-wrapper -->
  </div>
<!-- Menu Toggle Script -->
<script>
$('#menu-toggle').on('click', function(e){
  e.preventDefault();
  $('#wrapper').toggleClass('toggled');
});
</script>

</body>
</html>

app/views/pages/about.html.erb
<body>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-12 about-title">
        About Me
      </div>
      <div class="col-sm-4 profile-pic">
        <%= image_tag("Image01.jpg", :alt => "As a grad student") %>
      </div>
      <div class="col-sm-4 about-body">
        <p>
          Howdy readers, I am a full stack engineer learning my way through life.
          I wanted a single place to compile my thoughts and simultaneously
          improve my skills as a web developer. Hence 'Code Courage' was born.
        </p>
        <p>
           I would be adding more sections to the site, some required and some not
           so require ones. Feel free to send me feedback if something
           'offends/interests' you.
        </p>
        <p>
          This pic was taken in 2014 after a career fair. Since then much has changed.
          But I could not find another pic that I felt more comfortable with.
          As you see looks are not my strong suite :P
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 about-title">
        Interests
      </div>
      <div class="col-sm-4">
      </div>
      <div class="col-sm-4 interest-body">
        <p>
          Apart from being an amature cook, average photographer and a casual gamer.
          I like investing time in learning new technologies. Rails, Javascript, Java,
          API and front end design are right at the top of my technical interest list.
        </p>
        <p>
          Feel free to contact me if you want to connect. Thanks for reading.
          Have a great day!
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
      </div>
      <div class="col-sm-4">
      </div>
      <div class="col-sm-4">
        <div class="col-sm-1 social-links">
          <%= link_to(image_tag("linkedin-icon.png"), "https://www.linkedin.com/in/samarth-asthana-7a447014") %>
        </div>
        <div class="col-sm-1 social-links">
          <%= link_to(image_tag("github-icon.png"), "https://github.com/samarthasthana") %>
        </div>
        <div class="col-sm-1 social-links">
          <%= link_to(image_tag("twitter.png"), "https://twitter.com/samarthasthana") %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/posts/_form.html.erb
<body>
  <div class="container-fluid">
    <%= simple_form_for @post, :html=> { class: 'form-partial' } do |f| %>
      <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
          <%= f.input :title, :label => "Title", error: 'Should be 5 or more characters' %><br>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4"></div>
        <div class="col-sm-4">
          <%= f.input :body,  error: 'Should be 10 or more characters' %><br>
        </div>
      </div>
      <%= f.button :submit %>
    <% end %>
  </div>
</body>

app/views/posts/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <%= render 'form' %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="container-fluid">
  <% @posts.each do |post| %>
    <div class="row">
      <div class="col-sm-12 post-section">
        <h1 class="post-title"><%= link_to post.title, post %></h1>
        <div class="post-labels">
          <p><span class="post-label">Created on:</span>
            <%= post.created_at.strftime("%v") %>
          </p>
          <p><span class="post-label">Created by:</span>
            <%= post.user.email %>
          </p>
        </div>
        <p class="post-body">
          <%= raw post.body.truncate(50) %>
          <%= link_to 'Read more', post %>
        </p>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="col-sm-12">
      <%= paginate @posts %>
      <%= page_entries_info @posts %>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<h1>Create Post</h1>
<%= simple_form_for @post do |f| %>
  <%= f.input :title, error: 'Should be 5 or more characters' %><br>
  <%= f.input :body,  error: 'Should be 10 or more characters' %><br>
  <%= f.button :submit %>
<% end %>

app/views/posts/show.html.erb
<div class="container-fluid">
    <div class="row">
      <div class="col-sm-8 post-show">
        <h1 class="post-show-title"><%= @post.title %></h1>
        <p class="post-show-body"> <%=raw @post.body %></p>
        <p class="post-show-date">
          Submitted <%= time_ago_in_words(@post.created_at) %> Ago
          <% if user_signed_in? %>
          | <%= link_to 'Edit', edit_post_path(@post) %> |
            <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
        </p>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-8 comments">
        <div id="disqus_thread"></div>
          <script type="text/javascript">
          var disqus_config = function () {
          this.page.url = 'http://dev.samarthasthana.com' + '<%= request.original_fullpath.to_s%>'; // Replace PAGE_URL with your page's canonical URL variable
          this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
          };

          (function() { // DON'T EDIT BELOW THIS LINE
          var d = document, s = d.createElement('script');

          s.src = '//devsamarthasthanacom.disqus.com/embed.js';

          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
          })();
          </script>
        <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript" rel="nofollow">comments powered by Disqus.</a></noscript>
      </div>
      <script id="dsq-count-scr" src="//samarthasthana.disqus.com/count.js" async></script>
    </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>